import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sora = Sora({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // You can add more weights if needed
  variable: "--font-sora",
  display: "swap",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${sora.variable} bg-black antialiased`}>
        <div className="absolute inset-0 h-full min-h-screen backdrop-blur-md bg-black/[34%] z-0" />
        {children}
      </body>
    </html>
  );
}
