import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sora = Sora({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // You can add more weights if needed
  variable: "--font-sora",
  display: "swap",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-full">
      <body className={` ${sora.variable} bg-[#0D0814] antialiased`}>
        <div className="relative min-h-screen w-full">
          <div className="pointer-events-none absolute inset-0 z-0 w-full h-full">
            <div className="absolute inset-0 h-full min-h-screen backdrop-blur-sm bg-black/25" />
            {/* <div className="fixed inset-0 h-full min-h-screen bg-pattern " /> */}
            {/* Fixed pattern layer that works on mobile too */}
            <div className="fixed inset-0 z-0 bg-pattern bg-cover bg-center pointer-events-none" />
          </div>

          <div className="pointer-events-none absolute inset-0 z-5 w-full h-full">
            <div className="absolute inset-0 h-full min-h-screen backdrop-blur-xs  bg-black/10" />
          </div>

          <div className="relative z-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
